[package]
name = "axum_html_forms"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
html-node = { version = "0.2.1", features = ["typed"] }
serde = { version = "1.0.147", features = ["derive"] }
